// Copyright 2026 The go-ethereum Authors
// This file is part of the go-ethereum library.
//
// The go-ethereum library is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// The go-ethereum library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with the go-ethereum library. If not, see <http://www.gnu.org/licenses/>.

package etc

import (
	"math/big"
	"testing"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/consensus/ethash"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/params"
)

// ethTestPoWConfig mirrors the shape of the cmd/devp2p/internal/ethtest testdata
// chain: a perpetual PoW config with the Ethereum fork schedule and no ECIP keys.
// Such chains must validate byte-identically under the ETCEngine and standard
// ethash, since the engine is now selected by IsPow alone.
func ethTestPoWConfig() *params.ChainConfig {
	return &params.ChainConfig{
		ChainID:             big.NewInt(3503995874084926),
		HomesteadBlock:      big.NewInt(0),
		EIP150Block:         big.NewInt(6),
		EIP155Block:         big.NewInt(12),
		EIP158Block:         big.NewInt(12),
		ByzantiumBlock:      big.NewInt(18),
		ConstantinopleBlock: big.NewInt(24),
		PetersburgBlock:     big.NewInt(30),
		IstanbulBlock:       big.NewInt(36),
		MuirGlacierBlock:    big.NewInt(42),
		BerlinBlock:         big.NewInt(48),
		Ethash:              new(params.EthashConfig),
	}
}

// TestCalcDifficultyDelegatesWithoutBombKeys verifies that a PoW config carrying
// no ECIP bomb keys (ECIP1010Transition/ECIP1041Block) is delegated to the
// standard ethash difficulty schedule, so its Ethereum bomb-delay forks (e.g.
// Muir Glacier) are honored exactly. This protects the ethtest testdata chain,
// whose headers were generated by standard ethash.
func TestCalcDifficultyDelegatesWithoutBombKeys(t *testing.T) {
	config := ethTestPoWConfig()

	for _, tt := range []struct {
		name       string
		parentNum  int64
		uncleHash  common.Hash
		timeDelta  uint64
		parentDiff int64
	}{
		{"homestead", 3, types.EmptyUncleHash, 13, 131072},
		{"byzantium", 20, types.EmptyUncleHash, 13, 500000},
		{"byzantium_uncles", 20, common.HexToHash("0x01"), 13, 500000},
		{"muir_glacier", 50, types.EmptyUncleHash, 9, 1000000},
		{"deep_bomb_range", 5_000_000, types.EmptyUncleHash, 13, 2_000_000_000},
		{"deeper_bomb_range", 15_000_000, common.HexToHash("0x01"), 30, 3_000_000_000},
	} {
		t.Run(tt.name, func(t *testing.T) {
			parent := &types.Header{
				Number:     big.NewInt(tt.parentNum),
				Time:       1_600_000_000,
				Difficulty: big.NewInt(tt.parentDiff),
				UncleHash:  tt.uncleHash,
			}
			blockTime := parent.Time + tt.timeDelta
			got := CalcDifficultyETC(config, blockTime, parent)
			want := ethash.CalcDifficulty(config, blockTime, parent)
			if got.Cmp(want) != 0 {
				t.Errorf("parent %d: CalcDifficultyETC = %v, ethash.CalcDifficulty = %v", tt.parentNum, got, want)
			}
		})
	}
}

// TestCalcDifficultyBombKeysTakePrecedence verifies that when ECIP bomb keys are
// present the ETC schedule is used instead of the Ethereum one: inside Classic's
// DieHard pause the two schedules disagree, and a custom-chain-ID config with
// ECIP-1041 disposal keeps a zero bomb forever regardless of chain ID.
func TestCalcDifficultyBombKeysTakePrecedence(t *testing.T) {
	// Classic parent inside the DieHard pause window (3M..5M): the ETC bomb is
	// frozen at the 3M level while the raw (undelayed pre-Byzantium) schedule
	// would have kept growing, so the results must differ.
	parent := &types.Header{
		Number:     big.NewInt(4_000_000),
		Time:       1_500_000_000,
		Difficulty: big.NewInt(100_000_000_000),
		UncleHash:  types.EmptyUncleHash,
	}
	blockTime := parent.Time + uint64(13)
	etcDiff := CalcDifficultyETC(params.ClassicChainConfig, blockTime, parent)
	ethDiff := ethash.CalcDifficulty(params.ClassicChainConfig, blockTime, parent)
	if etcDiff.Cmp(ethDiff) == 0 {
		t.Errorf("Classic difficulty at 4M should differ from the ethash schedule, both = %v", etcDiff)
	}

	// A devnet-style config (custom chain ID, ECIP-1041 disposal at genesis)
	// must keep the bomb at zero at any height.
	devnet := ethTestPoWConfig()
	devnet.ChainID = big.NewInt(9999)
	devnet.ECIP1041Block = big.NewInt(0)
	for _, parentNum := range []int64{0, 199_999, 1_000_000, 20_000_000} {
		if got := calcBombComponentETC(devnet, big.NewInt(parentNum)); got.Sign() != 0 {
			t.Errorf("devnet bomb component at parent %d: got %v, want 0", parentNum, got)
		}
	}
}
